#!/usr/bin/env python3
print("Content-type: text/html\n")
print('<html>')
print('<head>')
print('<title>Hello Python!</title>')
print('</head>')
print('<body>')
print('<h2>Hello World!</h2>')
print('</body>')
print('</html>')