#!/usr/bin/env python3
import cgi, cgitb
print("Content-type: text/html\n")
form = cgi.FieldStorage()
user = form.getvalue('username')
print('<html>')
print('<head>')
print('<title>Sessions</title>')
print('</head>')
print('<body>')
print("<h2>Session 2: Hello")
print(user)
print("</h2>")
print(f"<a href='./py-sessions-1.py?={user}'>")
print("Session 1")
print("</a>")
print('<form action="./py-destroy-session.py" method=get><button type=submit>Destroy Session</button>')
print('</body>')
print('</html>')
#<a href='./py-sessions-2.py?={user}>