
name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Apache app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }} # password
          script: |
            cd test
            mkdir testdir
            mkdir rsynchere
            cd testdir
            git clone https://github.com/aazurill/CSE135.git
            rsync -a ./CSE135/www/* ../rsynchere
            rm -rf ./CSE135
            echo 'Deployment successful to digital ocean' 
